// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaceService.Application.Database;

#nullable disable

namespace RaceService.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620215335_21062026_addedIndexing")]
    partial class _21062026_addedIndexing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("RaceWins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.ToTable("Driver", (string)null);
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.PastResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceId", "Year");

                    b.ToTable("PastResult", (string)null);
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("Laps")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartTimeUTC")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartTimeUTC");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StartTimeUTC");

                    b.HasIndex("TrackId");

                    b.HasIndex("Status", "StartTimeUTC");

                    b.ToTable("Race", (string)null);
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CarManufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PUManufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RaceEntryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceEntry", (string)null);
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceEntryDriver", b =>
                {
                    b.Property<Guid>("RaceEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("RaceEntryId", "DriverId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceEntryId", "Role")
                        .IsUnique();

                    b.ToTable("RaceEntryDriver", (string)null);
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("BestLapTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<int>("LapsCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid>("PastResultId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("RaceEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartingPosition")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceEntryId");

                    b.HasIndex("PastResultId", "Position");

                    b.ToTable("RaceResult", (string)null);
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("BestLapTime")
                        .HasColumnType("interval");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("LengthInKm")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Track", (string)null);
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.PastResult", b =>
                {
                    b.HasOne("RaceService.Application.Domain.Entities.Race", "Race")
                        .WithMany("PastResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Race", b =>
                {
                    b.HasOne("RaceService.Application.Domain.Entities.Track", "Track")
                        .WithMany("Races")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceEntry", b =>
                {
                    b.HasOne("RaceService.Application.Domain.Entities.Race", "Race")
                        .WithMany("Entries")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceEntryDriver", b =>
                {
                    b.HasOne("RaceService.Application.Domain.Entities.Driver", "Driver")
                        .WithMany("RaceEntryDrivers")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceService.Application.Domain.Entities.RaceEntry", "RaceEntry")
                        .WithMany("Drivers")
                        .HasForeignKey("RaceEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("RaceEntry");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceResult", b =>
                {
                    b.HasOne("RaceService.Application.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceService.Application.Domain.Entities.PastResult", "PastResult")
                        .WithMany("RaceResults")
                        .HasForeignKey("PastResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceService.Application.Domain.Entities.RaceEntry", "RaceEntry")
                        .WithMany("Results")
                        .HasForeignKey("RaceEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("PastResult");

                    b.Navigation("RaceEntry");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Driver", b =>
                {
                    b.Navigation("RaceEntryDrivers");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.PastResult", b =>
                {
                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Race", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("PastResults");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceEntry", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Track", b =>
                {
                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
