// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaceService.Application.Database;

#nullable disable

namespace RaceService.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("RaceWins")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.PastResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RaceId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceId1");

                    b.ToTable("PastResult");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Laps")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTimeUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrackId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackId1");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CarManufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Driver1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Driver2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Driver3Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Driver4Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverResId")
                        .HasColumnType("uuid");

                    b.Property<string>("PUManufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RaceEntryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Driver1Id");

                    b.HasIndex("Driver2Id");

                    b.HasIndex("Driver3Id");

                    b.HasIndex("Driver4Id");

                    b.HasIndex("DriverResId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceEntry");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("BestLapTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<int>("LapsCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PastResultId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid>("RaceEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartingPosition")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("interval");

                    b.Property<int>("position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PastResultId");

                    b.HasIndex("RaceEntryId");

                    b.ToTable("RaceResult");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("BestLapTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LengthInKm")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.PastResult", b =>
                {
                    b.HasOne("RaceService.Application.Domain.Entities.Race", null)
                        .WithMany("PastResults")
                        .HasForeignKey("RaceId1");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Race", b =>
                {
                    b.HasOne("RaceService.Application.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceEntry", b =>
                {
                    b.HasOne("RaceService.Application.Domain.Entities.Driver", "Driver1")
                        .WithMany()
                        .HasForeignKey("Driver1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceService.Application.Domain.Entities.Driver", "Driver2")
                        .WithMany()
                        .HasForeignKey("Driver2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceService.Application.Domain.Entities.Driver", "Driver3")
                        .WithMany()
                        .HasForeignKey("Driver3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceService.Application.Domain.Entities.Driver", "Driver4")
                        .WithMany()
                        .HasForeignKey("Driver4Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceService.Application.Domain.Entities.Driver", "DriverRes")
                        .WithMany()
                        .HasForeignKey("DriverResId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaceService.Application.Domain.Entities.Race", null)
                        .WithMany("Entries")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver1");

                    b.Navigation("Driver2");

                    b.Navigation("Driver3");

                    b.Navigation("Driver4");

                    b.Navigation("DriverRes");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.RaceResult", b =>
                {
                    b.HasOne("RaceService.Application.Domain.Entities.PastResult", null)
                        .WithMany("RaceResults")
                        .HasForeignKey("PastResultId");

                    b.HasOne("RaceService.Application.Domain.Entities.RaceEntry", "RaceEntry")
                        .WithMany()
                        .HasForeignKey("RaceEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaceEntry");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.PastResult", b =>
                {
                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("RaceService.Application.Domain.Entities.Race", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("PastResults");
                });
#pragma warning restore 612, 618
        }
    }
}
